Grammar and content
===================
:toc:

== Grammar and content

Write clearly and consistently.

=== Tone and voice

Use the appropriate tone and voice in your content. Your content must be:

* Friendly and straightforward
* Clear and concise
* Inclusive and respectful
* Free of jargon and sales talk


=== Be brief and concise

Write short sentences and well-structured paragraphs. Don't repeat yourself.

*Example*

Yes: The style guide is a document with your brand colors and patterns. The style guide is important for user interface usability and consistency, as well as for adherence to your brand rules.

No: The Style Guide is a document with your brand theme colors and patterns ready to use to create a consistent user experience on your applications. It is an essential piece to ensure adherence to your brand rules, user interface consistency, and foster usability. It is designed to guide you through all delivery assets to optimize the development process and user experience.

=== Use American English

Use American English. This applies to spelling, word use, writing dates.

=== Use the present tense

Use the present tense whenever possible. Using the present tense helps make sentences clear and straightforward to understand.

*Example*

Yes: From time to time, OutSystems performs maintenance on the PaaS of their Customers.

No: From time to time, OutSystems will perform maintenance on the PaaS of their Customers.

=== Use contractions

Use common contractions instead of full forms. Some of the common contractions you need are: it's, doesn't, there's, can't/cannot.

Contractions help create friendlier and informal sentences, as full forms are generally reserved for formal writing. Avoid making contractions from a noun and a verb, especially with nouns denoting OutSystems products.

*Examples*

Yes: Don't use this function to encode text that might get executed as part of the SQL statement.

No: Do not use this function to encode text that might get executed as part of the SQL statement.

''''

Yes: Iterating more than once over a query result isn't a good practice.

No: Iterating more than once over a query result is not a good practice.

''''

Yes: LifeTime is an OutSystems management console.

No: LifeTime's an OutSystems management console. (No contractions with a noun, here a product name.)

=== Use the active voice

The active voice makes the sentence dynamic and clear. It also makes it clear who (the user, the system, and so forth) is doing what.

*Example*

Yes: After you validate the new SQL element, delete or deactivate the original Aggregate.

No: The original Aggregate is kept in the flow editor for your manual deletion after validating the new SQL element.

=== Be careful with the modal verbs

This section applies to the modal verbs can, could, may, might, will, shall, would, should, must. Modal verbs describe what you believe or think of the product, or they denote an ability or obligation. In contrast, technical content confidently describes what the product does. Using a modal instead of a stronger structure creates a weak and wordy sentence. It also makes your readers less confident about the content.

*Examples*

Yes: OutSystems lets you create several app types.

No: There are several app types you can create. (Here, "can" means ability, all people are able to create an app.)

''''

Yes: All customers with a valid and active Subscription are eligible for OutSystems Support.

No: All customers with a valid and active Subscription can contact OutSystems Support. (All people can dial a phone number.)

''''

Yes: OutSystems handles unforeseen or unhandled errors in applications.

No: OutSystems handles unforeseen or unhandled errors that might occur in applications. (If errors do happen, there's nothing hypothetical about their existence.)

=== Use second person

Use the second person "you" to address the reader or readers. However, don't overuse it.

Exceptions: You can use "we" when you're referring to OutSystems as a company. Use "I" in FAQs.

*Examples*

Yes: Review the configuration in Service Center.

No: Let us review the configuration in Service Center.

''''

Yes: In OutSystems, you model enumerates as Static Entity.

No: In OutSystems, we model enumerates as Static Entity. ("We" only loosely denotes OutSystems as a company. Compare to: "To focus our engineering resources innovative capabilities, we establish a cut-off date to end support for older code.")

''''

Yes: Keep in mind that, for a successful adoption of containers technology, you need skills in administering container infrastructures.

No: Keep in mind that, for a successful adoption of containers technology, customers will need skills in the administration of container infrastructures.

''''

Yes: How can I prevent accidental activations?

No: How can a developer prevent accidental activations? (This is from an FAQ section, where "I" fits well as it's a developer who's asking the question.)

=== Be clear and precise

The language in technical content must be  clear and precise. Clarity and precision make content useful to the audience. Check out the examples  that demonstrate how being vague, blaming users, or taking their time and skills for granted weakens clarity.

*Examples*

Yes: Do the following in all of your apps.

No: Some tasks must be used as a rule of the thumb (they apply to all kinds of applications). ("Some" and "all kinds of" are vague.)

''''

Yes: With this approach, you're not adding styles that can break the look and feel other developers created.

No: With this approach, you're not forcing things that people may not want in a particular scenario. (It's not clear what "thing" or "people" are.)

''''

Yes: Error. The library uses the API that's not available.

No: Error. The library might be using the API that's not available. ("Might" introduces doubt and doesn't make it clear whether the API is available or not.)

''''

Yes: You must create a package with all the applications, and deploy the package to your enterprise infrastructure.

No: Just create a package with all the applications, and deploy it to your enterprise infrastructure. ("Just" makes this task appear quicker to do than it seems. Using "simply" would imply the same false assumption.)

''''

Yes: If you activate this option, and your connection is poor,  debugging takes longer.

No: By activating this option, it's possible that the debugger will feel slower. (Using the verb "feel" is claiming that the slower performance is a subjective observation. It's not subjective.)

=== Keep accessibility in mind

Your content should be accessible to all people, to those without and with disabilities. Be mindful of:

* How you refer to people with disabilities. Use inclusive language.
* How you describe interactions with the user interface. Consider providing alternative methods or steps.
* How you use words to indicate a location (left, right, top, below, up, down) on screen. Provide more context for people using screen-readers.
* How you use the words "easy" and "simple". What may be simple to do for some people, it may not be simple to do for all.

See https://docs.microsoft.com/en-us/style-guide/accessibility/writing-all-abilities[Writing for all abilities] from Microsoft for more information.

=== Avoid the words "sorry" and "please"

Only use "sorry" for defects or situations related to OutSystems products, when there's, for example, a blocking error or a data loss. Only use "please" when you're asking users to do something that requires an extra effort.

=== Use sentence case for titles

Capitalize the first letter in titles.

Consult with the Technical Knowledge team if you're editing the main title of an already published article, as changes may affect the URL and make the page unavailable.

*Examples*

Yes: Configure application settings after deployment

No: Configure Application Settings After Deployment

''''

Yes: Use Actions to encapsulate logic

No: Use Actions to Encapsulate Logic

''''

Yes: Bootstrap an Entity using an Excel file

No: Bootstrap an Entity Using an Excel File

=== Use a comma to separate three or more items

When the coordinating conjunctions "and" or "or" precede the last item in a series, use a comma before the conjunction. The serial comma helps avoid confusion in cases where the last item in a series is a pair. If the items in the series are difficult to read or there's more than three, consider using a list.

*Examples*

Yes: Consider an infrastructure with the following environments: development, preproduction, and production.

No: Consider an infrastructure with the following environments: development, preproduction and production. (It may seem that there are two environments, the first running the apps in "development", and the second in "preproduction and production". However, there are  three different environments.)

''''

Yes: The sync client action sends the added, changed, and deleted local records to the server.

No: The sync client action sends the added, changed and deleted local records to the server. (The reader may understand that the local records need to be both changed and deleted before the client action sends the records to the server. However, both modification and deletion qualify a local record for a sync.)

''''

Yes: Service Center provides a set of metrics regarding a specific environment. It provides access to:

* Application logs and errors
* Web and mobile requests
* Integration calls
* Business processes
* Security audits

No: Service Center provides a set of metrics regarding a specific environment. It provides access to application logs and errors, web and mobile requests, integration calls, business processes, and security audits. (There are many items and a list works better here.)

=== Keep it international and straightforward to translate

Ensure your content is accessible to people of different cultures and with speakers of various levels of the English language. The following  are some guidelines to help you with that:

* Use plain English.
* Be consistent.
* Be inclusive. Inclusiveness also implies creating accessible content.
* When providing examples, whether visual or textual, be aware that not all examples work well across different cultures.
* Don't try to be funny. Humor doesn't work well in technical content.
* Don't use idioms. Idioms are difficult to translate and not all people know them.

*Example*

Here's an example of a copy: "It takes 23 years to become a Jedi, but it takes a lot less to master OutSystems - and it won't cost you an arm and a leg, or even a hand."

In Japan, the translators and editors removed the idiom "cost an arm and leg", and the humorous addition "or even a hand". They kept the Jedi reference, as it works well for their audience: "It takes 23 years to become a Jedi, but learning OutSystems takes less time. And you don't have to make a big sacrifice."

=== Use gender-inclusive language

You should make the gender visible only if it's important to understand the content. This means you shouldn't use words like he/she, himself/herself, man/woman, unless you're referring to a particular individual. Instead, use a non-gender alternative, like plural forms and "they". Furthermore, you shouldn't use language that reinforces stereotypes.

For more details, see https://docs.microsoft.com/en-us/style-guide/bias-free-communication[Bias-free communication] by Microsoft.

*Examples*

Yes:

* When developers download a Forge component, they can install it in Service Studio. (Use plural to avoid referring to gender.)
* When a developer downloads a Forge component, they can install it in Service Studio. (Use "they" to refer to a single person without mentioning their gender.)
* When you download a Forge component, install it in Service Studio. (Are your target readers developers? If yes, then "you" is a better choice.)

No:

* When a developer downloads a Forge component, he can install it in Service Studio. (Service Studio is not used exclusively by male developers or developers who identify as men.)

''''

Yes: We hope you'll join us for the upcoming User Group, and feel free to bring a guest.

No: We hope you'll join us for the upcoming User Group, and feel free to bring your husbands. (When you use the word "husband", you  assume someone is married.)

''''

Yes: We'd like to thank everyone in the community for such a great spirit.

No:  We'd like to thank our lady developers for making the community much more cheerful. (This is a discriminatory statement.)

=== Use standardized example domains

When providing examples of domain names, use one of the domains reserved for such use. For example, example.com. Don't use other domains nor any of our customer domains.

See https://tools.ietf.org/html/rfc6761[RFC 6761 - Special-Use Domain Names] for more information.

*Example*

Yes: Enter the email address, for example, john.smith@example.com.

No: Enter the email address, for example, john.smith@outsystems.com.

=== Check the readability scores

A readability score shows an estimated education level needed to understand a given text. Our content should be understood by high-school graduates.

=== Don't announce features and updates

Don't use documentation, training videos, or other technical content to inform users about future developments. Users need support with the product that is available to them.

*Example*

No: This feature currently has the following limitations that will be removed next month, in version 11.9.

Yes: This feature currently has the following limitations. Check the release notes page for information about the updates.

=== Avoid Latin abbreviations

Use "that is" instead of "i.e." and "for example" instead of "e.g.".

*Examples*

Yes: Design the behavior of the process (that is, the process flow) using the Process Flow.

No: Design the behavior of the process (i.e., the process flow) using the Process Flow.

''''

Yes: Make sure the Textarea Input has the Name property set (for example, myTextArea).

No: Make sure the Textarea Input has the Name property set (e.g., myTextArea).

=== Limit the git commit subject line to 50 characters

When writing git commit messages, be brief and limit the subject line (often the first line) to 50 characters. The subject line is visible in many places, and it's useful to know what the changes are by reading a one-line summary.
