Formatting
==========
:toc:

== Formatting

Use consistent formatting across all content.

=== Typographical emphasis

Bold. Use bold to denote the text as it's in the user interface. You can also use bold for occasional emphasis.

Italic. Don't use italic. Don't mix italic and bold.

Underline. Don't use underline, as browsers use it to show links.

*Examples*

In the *New Application* window select *Phone App* or *Tablet App* app template. 

Click *Generate App*.

Enter the information for the *Basics* blade and click *OK* to proceed to the next blade.

Choose *USERS* and click the *New User* link.

=== User inputs and interface labels

Use bold for interface labels, and write them with the same capitalization as they appear on the user interface.

To identify the text users need to enter, use a monospace font.  If you're using Markdown, use inline code to get a monospace font.

*Examples*

Enter `"display-flex"` in the input field.

Create a Container. Enter `MyContainer` in the *Name* property.

=== Variables and properties: names and values

Use bold for variable/property names and write them with the same capitalization as they appear on the UI. Use inline code for variable values.

*Example*

To restrict the elements to internal network access, set the *Internal Access Property* to `Yes`.

=== Keyboard shortcuts

Use sentence capitalization and spell the key name as it appears on the keyboard. Use bold when the shortcut appears in the sentence.

*Examples*

Ctrl+Shift+S

Esc

F1

To select all files, use *Ctrl+A*.

=== Code examples

Use code blocks for code examples. Specify the programming language of the example code, if your text editor has that option.

*Example*

A JavaScrip code snippet:

[source, javascript]
----
// Return success in GlobalAsyncAction client action
$parameters.Success = true;
$parameters.Out1 = 5.0;
$resolve();
----

A JSON code snippet:

----
{
    "plugin": {
        // Use only one the following ways to reference a plugin
        "url": "<The url to a public git repository containing your plugin>",
        // or
        "identifier": "<The identifier for your plugin>",
        // or
        "resource": "<The path to the plugin folder inside the resources file ZIP>",
        // If the plugin requires additional settings
        "variables": [
            {
                "name": "<The attribute name for your plugin variable>",
                "value": "<The attribute value for your plugin variable>"
            },
            /* ...more variables, if needed... */
        ]
    }
}
----

=== Screenshots and illustrations

Screenshots and illustrations should be a useful addition to the content, and not critical to the understanding of the content or following a procedure.

* Use screenshots to guide users in a complicated or long procedure, to show complex windows or dialog boxes, or to emphasize a new feature.
* The screenshot should show the relevant part of the user interface and some of the surrounding interface, for the users to know where to locate the relevant part. For example, if you need a screenshot with an input field, include the form or a window where the field shows. However, don't use the screenshot of the entire desktop.
* Mask the internal domain names and user names of OutSystems employees in your screenshots.
* The maximum screenshot size is 1200 pixels wide, with screen scale set at 100%. When highlighting an area on a screenshot, only use boxes and arrows. Use "Bright Red" (#F22800) and stroke dimension 2pt.
* Give unique and meaningful names to the screenshot files. Use lowercase and hyphens between words. For example, "vpn-your-outsystems-cloud.png".
* For public content, only use products that are generally available.
* If you're using screenshots from a third-party product, check the copyright notes for the product and the rules for the screenshot use.

=== Writing ALT Text

There are several benefits to using Alt text, such as:

* Helps to create a better user experience for all users
* Displays in place of an image on a web page when the image doesn't load
* Enables screen readers to describe images to a visually impaired reader, which improves accessibility
* Helps to improve our rankings with search engines by surfacing our images

=== How to write alt-text for images

When writing alt-text, keep the following in mind: 

* Describe the image and be specific - use the image subject and some context 
* Add context that relates to the topic of the page. 
* Include the content and purpose of an image.  Keep the text to a sentence or two. Try to limit the number of characters to between 125 and 150. Think about what is important in the image. What are you trying to convey? If you have a complex image  (screenshot), add information before the image. 
* Don't start alt text with "picture of..." or "Image of..." or “Screenshot of” - these words don’t add value; instead, start with the description. Explain what the image shows, such as “ODC studio logic tab. Screen-reading tools (and Google, for that matter) will identify it as an image from the article's HTML source code. 
* Prioritize information - put the most important information at the beginning
* Use text that is in the image in the alt-text
* Capitalize the first letter
* End whole sentences with a period
* Don’t include superfluous information

=== Alt text examples

