Content structure
=================
:toc:

== Content structure

This section is about organizing content in documentation and training.

== Structure in documentation

Notes about different parts of documents.

=== Include an introduction / overview

Begin the document with an introduction / overview to let readers know what to expect in the document and it confirms they found what they were looking for. 

=== Place prerequisites near the top

Place prerequisites at the beginning of the document. This sets the users' expectations because they immediately know if they can use this document or not. Keep in mind that prerequisites might end up as preview snippets in search engines results page.

=== Use admonitions sparingly

Only use admonitions ("infoboxes", warnings, errors) when you need to emphasize a piece of information. The overuse of admonitions has the opposite effect, as readers start ignoring them.

For the list of admonitions you can use, see: link:markdown.adoc[Warning and information boxes]

=== Limit the number of steps in procedures

Try limiting procedures to seven to nine steps. This is to prevent us from writing endless procedures that are difficult to follow.  If you need more steps, consider reorganizing the content.

=== Use links in paragraphs occasionally

Having too many links distracts the reader from understanding the content. Additionally, those links are difficult to maintain. Limit the number of links in a text to ones that are necessary for users to achieve a task.

Don't add links to every concept just because you have content about it. Use the See Also section to list related documents.

*Example*

Yes:  Use http://example.com/[Extract to Action] to create a new Action with that piece of logic.

No:  Use http://example.com/[Extract to Action] to create a http://example.com/[new Action] with that piece of http://example.com/[logic].

=== Use heading levels 

Use heading levels to show the relationship of ideas and to enable readers to easily scan and read selectively. 

=== Limit headings to three levels

Avoid using more than three levels of headings. If you think that you need more levels to structure the content, consider separating the content into smaller documents. 

=== Add content after a heading

Add at least a sentence between a heading and an image or table, describing what follows.

*Example*

Yes:

*Create a New Mobile App*

Follow the following steps to create a new mobile app.

1. ...
2. ...
3. ...

No:

*Create a New Mobile App*

1. ...
2. ...
3. ...

=== Add a summary

Add a summary to your document/video explaining why users might need the content. The summary shows in Google results pages.

*Example*

Develop a Progressive Web App (PWA) by creating a Mobile App and toggling on the option to distribute the app as PWA. Try your app in Android and iOS.

=== Differentiate content for technical preview features

Documentation for Technical Preview (TP) features is typically self-contained. Here's how a document for a TP feature is different from a document for a feature that's Generally Available (GA).

* *Title*. The title is "Technical Preview - <title>".
* *Technical Preview infobox*. Place an infobox at the beginning of the page clarifying that it's a Technical Preview feature. The default message is: "Read https://success.outsystems.com/Support/Enterprise_Customers/Upgrading/Technical_Preview_features[how features in Technical Preview work]. We encourage you to try these features out and to http://example.com/[send us your feedback].". Check with the Technical Knowledge team where the "send us your feedback" should link to, or if the message should be different.
* *Table of content listing*. Check with the Technical Knowledge team if you should include the page in the table of content or to have it accessible as a direct link only.

*Example*

See https://success.outsystems.com/Documentation/11/Managing_the_Applications_Lifecycle/Deploy_Applications/Technical_Preview-_Configure_Site_Properties_During_Deployment[Technical Preview - Configure Site Properties During Deployment].

== Structure in training

How to structure videos in training to make them useful and engaging.

=== Slide decks

Limit the length of videos to four minutes. Avoid using screenshots in videos created from slide decks to show steps. Show the steps through the demo videos instead.

=== Demos

Each demo should be self-contained. Use a pre-built demo for a quick start, as it has a scenario that focuses on the topic.

=== Quizzes

Each question is a multiple-choice question and has between two and four (preferred) choices.

For each answer, give a rationale and explain to the user why the answer is correct or incorrect.

Within a question, two answers cannot be mutually exclusive. Logically, this doesn't apply to the questions with only two answers.

All choices should be plausible enough to be considered possibly correct.

=== Exercises

Ideally, provide a sample app for a quick start and explain how to install it. The sample app should be self-contained, without dependencies, and have all the resources users need for following the training video.
